
services:
  local-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=itjustworks
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    

 api-server:
    image: lms-public-api
    build: api/
    environment:
      - MODE=local
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:lms123@local-db:5432/mydb
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - local-db

  web-server:
    image: lms-web
    build: webapp/
    environment:
      - MODE=local
      - API_URL=http://api-server:8080
    ports:
      - "3000:80"
    depends_on:
      - api-server
